---
booktitle: Proceedings of the Eighth International Conference on Probabilistic Graphical
  Models
shortname: PGM 2016
year: '2016'
published: 2016-08-15
start: 2016-09-06
end: 2016-09-09
volume: 52
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: pgm2016
month: 0
cycles: false
editor:
- given: Alessandro
  family: Antonucci
- given: Giorgio
  family: Corani
- given: Cassio Polpo
  family: Campos}
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Eighth International Conference on Probabilistic Graphical Models
    Held in Lugano, Switzerland on 06-09 September 2016

  Published as Volume 52 by the Proceedings of Machine Learning Research on 15 August 2016.

  Volume Edited by:
    Alessandro Antonucci
    Giorgio Corani
    Cassio Polpo Campos}

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 06--09 Sep
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v52"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v52
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Probabilistic Graphical Models
  url: http://www2.idsia.ch/cms/pgm/
  location: Lugano, Switzerland
  dates:
  - 2016-09-06
  - 2016-09-07
  - 2016-09-08
  - 2016-09-09
  number: 8
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
